### PR TITLE
Update docs to describe new attribute id usage to filter groups

### PR DESCRIPTION
**Pull request by zachgoldstein**
Closes https://github.com/airbrake/airbrake-docs/issues/133

Update API documentation to describe new 2-step attribute process for filter groups

### CODE REVIEW

**Comment by zachgoldstein** [comment]
@vmihailenco could you confirm that this accurately describes the current process for filter groups.

**Comment by vmihailenco** [comment]
What about just removing unsupported API and not adding anything? Most likely there will be 1 external user of this API, but we will have to maintain it forever.

**Comment by zachgoldstein** [comment]
I think we need to show in the docs how to filter groups. I don't think it's very nice to just drop functionality from the API without giving users an alternative. Especially without a deprecation message or any warning. This is definitely not a core feature but the support ticket that sparked this had a customer who had his entire build system go down because of us. For every person who tells us about this there's going to be another 10 who don't say anything and are just silently pissed off.

So I think we need *something*, and there's more than 1 user.

Personally I'd rather just keep the old endpoints and use the attribute pieces inside goab, behind the scenes. I feel the old endpoints were much much more convenient.

**Comment by zachgoldstein** [comment]
I'm not sure how to move forward here. @zefer do you have any thoughts on this?

**Comment by zefer** [comment]
Can we mark it as deprecated rather than remove it? If we find a situation where we need to remove it or are struggling to support it, we can collect usage data and contact those who are known to be using it with date.

**Comment by zachgoldstein** [comment]
We haven't really gotten anybody else complaining about this over the last 2 weeks so I see what you're saying @vmihailenco. You feel strongly about this right? I'll edit this to remove the old api docs. 

@zefer if we list it as deprecated doesn't that mean it should still work? It's gone afaik. I'd prefer to just remove it at this point.

**Pull request merged**
