### PR TITLE
index: delete unwanted "shell" language

### PR DESCRIPTION
**Pull request by kyrylo**
Before | After
-- | --
airbrake api reference 2017-05-18 23-03-49 | airbrake api reference 2017-05-18 23-03-35

### CODE REVIEW

**Comment by sgray** [comment]
Why is it unwanted?

**Comment by vmihailenco** [comment]
Seems fine, leaving for @sgray

**Comment by kyrylo** [comment]
@sgray at first, I was confused about the black bar. I thought it was some visual bug. When I read your comment, I realised it's "tabs".

It is unwanted because it is:

1. Confusing
2. We only have one language, so it serves no purpose
3. The language we display is not only shell, but a mixture of sh and JSON

**Comment by sgray** [comment]
I don't really mind either way. I don't find it confusing because the examples are all using the shell. The places that show JSON are still using cURL to send it.

**Comment by kyrylo** [comment]
Some places don't use curl. Anyhow, if you don't mind, then let's merge?

**Comment by sgray** [comment]
👍

**Pull request merged**
