### PR TITLE
Standardise title formatting: use normal case throughout

### PR DESCRIPTION
**Pull request by zefer**

### CODE REVIEW

**Comment by dvdplm** [comment]
This is defo my preferred style of casing. It is not however the US standard (e.g. http://grammar.about.com/od/grammarfaq/f/capitalstitle.htm). I say we go with this, but it might be worth noting.

**Comment by mmcdaris** [comment]
Nice info @dvdplm!
:+1: for (Sentence case/Down style)! LGTM

**Comment by vmihailenco** [comment]
LGTM. Thanks.

**Comment by zefer** [comment]
Pretty cool @dvdplm, there's all sorts of names for these different styles!

**Pull request merged**
