### PR TITLE
Link to deploy docs in the README

### PR DESCRIPTION
**Pull request by mmcdaris**
Provide a link to the [Deploy slate](https://github.com/airbrake/ansible/wiki/Deploy-slate) ansible wiki doc.

### CODE REVIEW

**Comment by mmcdaris** [comment]
@kyrylo and I both wondered how to deploy slate so I thought this might prevent any other teammates from pondering the same thing.

**Comment by kyrylo** [comment]
LGTM :ok_hand:  :cow: :+1:

**Comment by vmihailenco** [comment]
We probably should make this a private repository if we start adding links to private repos.

**Comment by kyrylo** [comment]
I haven't realised it's public :)

**Comment by mmcdaris** [comment]
@vmihailenco great point! 
I didn't think of that one! I made some room! Is it cool to convert this repo to private?

**Comment by mmcdaris** [comment]
On second thought I think at this point it's enough to just have an ansible wiki doc.
If we turn this repo private then we will never get any community contributions as @zefer brought up:
> It’s intentional that our API docs are public, the theory is that people can submit PRs to fix them, or browse them It’s good discipline too. Ideally, IMO, all of our knowledge-base would be opensource, too. [slack archive](https://airbrake.slack.com/archives/dev/p1457024340000096)

Closing this one out as the tradeoff for a deploy link is not worth privatizing the repo.

**Pull request closed without merging**
